### ISSUE TITLE
[FEA] CUDA 11.6 support

### ISSUE THREAD

**Issue by paravatha** [rapidsai/docs#246]
**Is your feature request related to a problem? Please describe.**

Currently, I only see CUDA versions 11.0, 11.2, 11.4 and 11.5 in the "RAPIDS RELEASE SELECTOR" on this page
https://rapids.ai/start.html#get-rapids

**Describe the solution you'd like**
Requesting support for CUDA 11.6

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bdice** [comment]
RAPIDS can be installed with other CUDA minor versions, such as 11.6. This works through CUDA Enhanced Compatibility, which has been supported since the 21.12 release ([RGN 19](https://docs.rapids.ai/notices/rgn0019/)). Please see the CUDA docs on compatibility for more information: https://docs.nvidia.com/deploy/cuda-compatibility/

RAPIDS fully tests only a subset of all CUDA minor versions, which I think currently includes 11.4, 11.8, 12.0 (and possibly others). The testing matrix is usually aligned with the versions advertised in the installation instructions. Please refer to https://docs.rapids.ai/notices for notices about any changes in CUDA version support. Closing this as complete.
