### ISSUE TITLE
[FEA] Add other install methods to Selector tool?

### ISSUE THREAD

**Issue by raybellwaves** [rapidsai/docs#498]
**Is your feature request related to a problem? Please describe.**

Wonder if it's worth adding other install methods into the selector tool (https://docs.rapids.ai/install#selector) such as uv (https://github.com/astral-sh/uv) and pixi (https://pixi.sh/latest/)?

**Describe the solution you'd like**
Perhaps additional boxes in the selector tool or comments around replacements e.g. `uv pip` for `pip`.

**Describe alternatives you've considered**
I understand adding a few new package management tools who release often runs the risk that it may break things. You also need additional documentation on using them and troubleshooting. They also may not be mature enough that's they are worth including.

**Additional context**
Recently saw ibis has pixi in their install docs https://ibis-project.org/install 

Recently got a nice speed up (275%) using `uv pip` vs `pip` on google colab (https://colab.research.google.com/drive/1d3_gb_4y2Xgvl6xBBdknfwUV8Heq-nzJ)

pixi may offer speed up downloading conda packages but I haven't worked a clean rapids install yet (https://github.com/prefix-dev/pixi/discussions/1029)

**Comment by bdice** [comment]
I left some thoughts on the PR: https://github.com/rapidsai/docs/pull/510#issuecomment-2065170581

Overall, RAPIDS aims to support the most stable and well-recognized installation methods like `pip` and `conda`. If we see increased interest in using other tools, we can definitely re-evaluate the RAPIDS documentation in the future. For now, I'll close this issue since I don't think there are short-term actions. However, we can continue conversation and I'll reference this issue in the future if we see interest grow as tools become more mainstream. We welcome issues reports from users of `uv`, `pixi`, etc. if there are ways that RAPIDS packages need to be improved.
